layout_spectrum: 0.9426523
color:
  saturation: 0.9683819
  lightness: 0.3714858
  brandStrength: 0.903145
  brandColors:
    - '#1F150D'
    - '#FFFFFF'
    - '#E0B35D'
    - '#887F80'
    - '#5C432F'
  rhythmicContrast: 0.2295523
typography_spectrum: 0.9408602
name: 'Charcoal '
